name: CI

run-name: "CI ${{ github.ref_type }} ${{ github.ref_name }}: '${{ github.event.head_commit.message }}'"

"on": [push]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NIXPKGS_VERSION: "25.11"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version: "0.9.18"
          enable-cache: true
      - name: Install node
        run: bash -c 'source "${NVM_DIR}/nvm.sh" && nvm install'
      - name: Install zsh
        run: sudo apt-get install zsh
      - name: Install nix
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:nixos-${{ env.NIXPKGS_VERSION }}
      - name: Install emacs
        run: nix profile add "nixpkgs/release-${NIXPKGS_VERSION}#emacs-nox"
      - name: Run tests
        env:
          TERM: dumb
        run: make ci
