name: CI

run-name: "CI ${{ github.ref_type }} ${{ github.ref_name }}: '${{ github.event.head_commit.message }}'"

"on": [push]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NIXPKGS_VERSION: "25.11"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.9.18"
          enable-cache: true
      - name: Install node
        run: bash -c 'source "${NVM_DIR}/nvm.sh" && nvm install'
      - name: Install zsh
        run: sudo apt-get install zsh
      - name: Install nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
        with:
          nix_path: nixpkgs=channel:nixos-${{ env.NIXPKGS_VERSION }}
      - name: Install emacs
        run: nix profile add "nixpkgs/release-${NIXPKGS_VERSION}#emacs-nox"
      - name: Run tests
        env:
          TERM: dumb
        run: make ci
